export const CHANGE_COLOR = 'CHANGE_COLOR';

export const INIT_SATURATION = 'INIT_SATURATION';

export const ADD_COLOR = 'ADD_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const BULK_REMOVE = 'BULK_REMOVE';
export const BULK_INSERT = 'BULK_INSERT';

export const INIT_MIXER = 'INIT_MIXER';
export const CHANGE_MIX_COLOR = 'CHANGE_MIX_COLOR';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const SCHEMES_FETCH_START = 'SCHEMES_FETCH_START';
export const SCHEMES_FETCH_SUCCESS = 'SCHEMES_FETCH_SUCCESS';
export const SCHEMES_FETCH_ERROR = 'SCHEMES_FETCH_ERROR';